openapi: "3.0.3"
info:
  title: Orders
  version: "1.0"
servers:
  - url: http://localhost:8080

paths:
  /orders:
    get:
      tags:
        - orders
      summary: "Получение всех заказов"
      description: "Получение всех заказов"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
    post:
      tags:
        - orders
      summary: "Создать новый заказ"
      description: "Создать новый заказ"
      parameters: []
      requestBody:
        description: Cоздать новый заказ
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderBody"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "404":
          description: Wrong data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Нет имени заказа"
                    description: "Ошибка создания заказа"
  /orders/{id}/status:
    put:
      tags:
        - orders
      summary: "Обновить статус существующего заказа"
      description: "Обновить статус существующего заказа"
      parameters:
        - name: id
          in: path
          description: ID заказа
          required: true
          schema:
            type: string
            format: string

      requestBody:
        description: Обновить статус существующего заказа
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateOrderStatus"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "404":
          description: Wrong data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Нет имени заказа"
                    description: "Ошибка создания заказа"
  /orders-page:
    get:
      tags:
        - pages
      summary: "Страница для просмотра всех заказов"
      description: "Страница для просмотра всех заказов"
      responses:
        "200":
          description: Successful operation
          content:
            text/html:
              schema:
                type: string

  /create-order-page:
    get:
      tags:
        - pages
      summary: "Страница для создания заказа"
      description: "Страница для создания заказа"
      responses:
        "200":
          description: Successful operation
          content:
            text/html:
              schema:
                type: string

  /change-order-status-page/{id}:
    get:
      tags:
        - pages
      parameters:
        - name: id
          in: path
          description: ID заказа
          required: true
          schema:
            type: string
            format: string

      summary: "Страница для изменения статуса заказа"
      description: "Страница для изменения статуса заказа"
      responses:
        "200":
          description: Successful operation
          content:
            text/html:
              schema:
                type: string

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
          example: "1"
          description: "ID заказа"
        name:
          type: string
          example: "Order-Name"
          description: "Название заказа"
        author:
          type: string
          example: "email@gmail.com"
          description: "Email-пользователя, который создал заказ"
        status:
          type: string
          example: created
          enum:
            - created
            - in_progress
            - finished
            - canceled
            - deleted
    UpdateOrderStatus:
      required:
        - status
      type: object
      properties:
        status:
          type: string
          example: created
          enum:
            - created
            - in_progress
            - finished
            - canceled
            - deleted
    CreateOrderBody:
      required:
        - name
        - author
      type: object
      properties:
        name:
          type: string
          example: "Order-Name"
          description: "Название заказа"
        author:
          type: string
          example: "email@gmail.com"
          description: "Email-пользователя, который создал заказ"
